# Generated by Django 2.2.19 on 2021-04-29 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('contenuto', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('commenti', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=20)),
                ('Cognome', models.CharField(max_length=20)),
                ('Data_di_nascita', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Nickname', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Articolo',
        ),
        migrations.DeleteModel(
            name='Giornalista',
        ),
        migrations.AddField(
            model_name='post',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Utente'),
        ),
    ]
