# Generated by Django 2.2.19 on 2021-05-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210430_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='Data_di_nascita',
            field=models.DateTimeField(),
        ),
    ]
